### PR TITLE
[Zenith] L-3 Missing assertions for equal points in add_montgomery

### LINKED ISSUE #20: [Zenith] bug(g1,g2): Missing assertions for equal points in add_montgomery
### Target

- [src/gadgets/bn254/g1.rs](https://github.com/alpenlabs/g16/blob/7d7e002ac9a78700e475750dd45a3672edf394f7/src/gadgets/bn254/g1.rs#L160)
- [src/gadgets/bn254/g2.rs](https://github.com/alpenlabs/g16/blob/7d7e002ac9a78700e475750dd45a3672edf394f7/src/gadgets/bn254/g2.rs#L211)

### Severity:

- Impact: High
- Likelihood: low

### Description:
The `add_montgomery` function uses point addition method using Jacobian Projective Coordinates as mentioned in the [ref](http://koclab.cs.ucsb.edu/teaching/ccs130h/2018/09projective.pdf). It must be noted that the method is applicable only for points P, Q such that $P, Q \ne infinity$ and $Q \ne P$ as mentioned in the pdf. The implementation however only takes into the account $P, Q \ne infinity$ by checking if the z-coordinate of either input is 0 and uses a multiplexer to return the other point but fails to have a check that  $Q \ne \pm P$. The $Q \ne -P$ holds implicitly but $Q \ne P$ does not (point doubling done separately). Right now in the codebase it is used for the scalar multiplication and msm so this can be a deliberate optimization but if the function is exposed as a general purpose fn to construct circuits, this can be an issue and can be exploited. 

### Recommendations:
If the gadgets is strictly for internal components then checks can be avoided as the algorithm naturally avoids $P = Q$ but if the function is exposed as public where p and q are directly provided by user then circuit assertions should be added to ensure that $P \ne Q$.

**Client:**

**Zenith:**

### PR DESCRIPTION
**Pull request by manishbista28**
Fixes #20

### CODE REVIEW

File: g16ckt/src/gadgets/bn254/g1.rs [hunk 1]
```diff
@@ -391,6 +392,9 @@ impl G1Projective {
             ));
         }
 
+        // given two bases M and N which were both known in compile time,
```
Comment (AaronFeickert) [inline g16ckt/src/gadgets/bn254/g1.rs:395]: For this case, can we assume that `M` and `N` have no efficiently-computable discrete logarithm relation?

Comment (manishbista28) [reply g16ckt/src/gadgets/bn254/g1.rs:395]: M and N are public input commitment part of verification keys, so I assume M and N do not have efficiently-computable discrete log relation.
If they did, you'd be able to supply scalars a or b such that [a]M = [b]N.
Without [a]M = [b]N, there won't be a case where input to add_montgomery(circuit, [a]M, [b]N) will have same value of operands. Thus the equal points in add_montgomery will not hit.

Comment (AaronFeickert) [reply g16ckt/src/gadgets/bn254/g1.rs:395]: Let's double-check the claim that as part of the verification keys, they cannot have a known discrete logarithm relation.

Comment (AaronFeickert) [reply g16ckt/src/gadgets/bn254/g1.rs:395]: ^ @manishbista28

Comment (AaronFeickert) [reply g16ckt/src/gadgets/bn254/g1.rs:395]: @manishbista28 are we good on this?

Comment (manishbista28) [reply g16ckt/src/gadgets/bn254/g1.rs:395]: verification keys do not have a known computable discrete logarithm relation because the verifier doesn't know the trapdoor from which these input commitment components are made.
so we're good on this.

Comment (manishbista28) [reply g16ckt/src/gadgets/bn254/g1.rs:395]: https://github.com/arkworks-rs/groth16/blob/master/src/data_structures.rs#L41
Here, alpha, beta and gamma are trapdoors.

**Review by AaronFeickert — APPROVED** [review]
